routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Route::get('testmail', function(){
//     $to_name = 'lester';
//     $to_email = 'clarenista@gmail.com';
//     $data = array('name'=>'nrl', 'body' => 'A test mail');
//     Mail::send('emails.mail', $data, function($message) use ($to_name, $to_email) {
//         $message->to($to_email, $to_name)
//         ->subject('Laravel Test Mail');
//     $message->from('mail.nrldoh@gmail.com','Test Mail');
//     });
// });

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes(['register' => false]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/certificate/{key}/verify/', [App\Http\Controllers\Guest\CertificateController::class, 'verify'])->name('verifyCertificate');
Route::put('/certificate/{key}/verify/', [App\Http\Controllers\Guest\CertificateController::class, 'updateVerifyByFacility'])->name('verifyMyCertificate');
Route::group(['middleware' => ['role_or_permission:admin|create facility', 'auth']], function () {
    //
    Route::resource('/facilities', App\Http\Controllers\FacilityController::class);
    Route::post('/facilities/createOrUpdate', [App\Http\Controllers\FacilityController::class, 'createOrUpdate'])->name('facilities.createOrUpdate');
});
Route::group(['middleware' => ['role_or_permission:admin|create user', 'auth']], function () {
    Route::resource('/users', App\Http\Controllers\UserController::class);
});

Route::name('settings.')->group(function () {
    Route::group(['middleware' => ['auth']], function () {

        Route::get('/settings', [App\Http\Controllers\SettingController::class, 'index'])->name('index');
        Route::put('/settings/certificate', [App\Http\Controllers\SettingController::class, 'storeCertSettings'])->name('storeCertSettings');
    });
});


Route::prefix('verifier')->group(function () {
    Route::name('verifiers.facilities.')->group(function () {
        Route::group(['middleware' => ['auth']], function () {
            Route::get('/email/preview', [App\Http\Controllers\Verifier\FacilityController::class, 'emailPrev']);
            Route::get('/facilities', [App\Http\Controllers\Verifier\FacilityController::class, 'index'])->name('index');
            Route::post('/facilities', [App\Http\Controllers\Verifier\FacilityController::class, 'search'])->name('search');
            Route::get('/facilities/{id}', [App\Http\Controllers\Verifier\FacilityController::class, 'show'])->name('show');
            Route::group(['middleware' => ['role:encoder']], function () {
                Route::put('/facilities/{id}/certificate/{cert_id}/updatePrepared', [App\Http\Controllers\Verifier\FacilityController::class, 'updatePrepared'])->name('updatePrepared');
                Route::post('/facilities/{id}/certificate/create', [App\Http\Controllers\Verifier\FacilityController::class, 'create_certificate'])->name('create_certificate');
                Route::put('/certificate/{id}/edit', [App\Http\Controllers\Verifier\FacilityController::class, 'edit_certificate'])->name('edit_certificate');
            });
            Route::group(['middleware' => ['role:verifier']], function () {
                Route::put('/facilities/{id}/certificate/{cert_id}/updateVerified', [App\Http\Controllers\Verifier\FacilityController::class, 'updateVerified'])->name('updateVerified');
            });

            Route::group(['middleware' => ['role:head']], function () {
                Route::resource('/users', App\Http\Controllers\UserController::class);
                Route::put('/facilities/{id}/certificate/{cert_id}/updateApproved', [App\Http\Controllers\Verifier\FacilityController::class, 'updateApproved'])->name('updateApproved');
                Route::post('/facilities/{id}/certificate/{cert_id}/emailFacility', [App\Http\Controllers\Verifier\FacilityController::class, 'emailFacility'])->name('emailFacility');
            });
        });
    });
});
// certificate
Route::get('/certificate/{key}', [App\Http\Controllers\Verifier\FacilityController::class, 'certificate'])->name('certificate');

// PT

Route::group(['middleware' => ['role:admin']], function () {
    Route::resource('/proficiency-testing', App\Http\Controllers\ProficiencyTestingController::class);
    Route::name('proficiency-testing.')->group(function () {
        Route::get('/proficiency-testing/{id}/applicants', [App\Http\Controllers\ProficiencyTestingController::class, 'applicants'])->name('applicants');
        Route::put('/proficiency-testing/{id}/applicants/{application_id}', [App\Http\Controllers\ProficiencyTestingController::class, 'sendSpecimen'])->name('applicants.sendSpecimen');
        Route::put('/proficiency-testing/{id}/applicants/{application_id}/verifyPayment', [App\Http\Controllers\ProficiencyTestingController::class, 'verifyPayment'])->name('applicants.verifyPayment');
    });
});

Route::prefix('facility')->group(function () {
    Route::name('proficiency-testing.facility.')->group(function () {
        Route::get('/proficiency-testing', [App\Http\Controllers\Facility\ProficiencyTestingController::class, 'index'])->name('index');
        Route::get('/proficiency-testing/{id}', [App\Http\Controllers\Facility\ProficiencyTestingController::class, 'apply'])->name('apply');
        Route::post('/proficiency-testing/{id}', [App\Http\Controllers\Facility\ProficiencyTestingController::class, 'saveApplication'])->name('saveApplication');
        Route::put('/proficiency-testing/{id}', [App\Http\Controllers\Facility\ProficiencyTestingController::class, 'saveReceipt'])->name('saveReceipt');
        Route::put('/proficiency-testing/{id}/receiveSpecimen', [App\Http\Controllers\Facility\ProficiencyTestingController::class, 'receiveSpecimen'])->name('receiveSpecimen');
    });
});

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;

    protected $fillable = [
        'certificate_theme', 'certificate_given_at', 'updated_by'
    ];
}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Setting;

class SettingController extends Controller
{
    function index(){
        $settings = Setting::find(1);
        return view('settings.index', compact('settings'));
    }

    function storeCertSettings(Request $request){
        $validated = $request->validate([
            'certificate_theme' => ['required', 'string', 'max:80'],
        ]);
        $settings = Setting::find(1);
        $request->merge(['updated_by' => \auth()->id()]);
        $settings->update($request->all());
        return redirect()->route('settings.index')->with('message', 'Settings has been saved.')->with('classname', 'alert-success');
    }
}

resources/views/settings/index.blade.php
@extends('layouts.main')

@section('title')
NRL - Facilities
@endsection

@section('content')



    @if(Session::has('message'))
    <div class="alert {{session('classname')}}">
        {{session('message')}}
    </div>
    @endif

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800"> Settings</h1>
    </div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#certificate">Certificate</a>
        </li>
        
    </ul>

    
    <!-- Tab panes -->
    <div class="tab-content mt-4">
        <div class="tab-pane container active" id="certificate">
            <div class="row">
                <div class="col-md-5 col-sm-12">
                    
                    <form method="post" action="{{route('settings.storeCertSettings')}}">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="theme">Theme</label>
                            <textarea id="theme" class="form-control @error('certificate_theme') is-invalid @enderror"  name="certificate_theme" rows="3">{{$settings->certificate_theme}}</textarea>
                            @error('certificate_theme')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="given_on">Given on</label>
                            <input id="given_on" class="form-control" value="{{$settings->certificate_given_at}}" name="certificate_given_at" type="date">
                        </div>
                        <!-- Divider -->
                        <hr class="sidebar-divider d-none d-md-block">
                        <button class="btn btn-primary" type="submit">Update</button>
                    </form>
                </div>
                <div class="col-md col-sm-12" id='preview' style=" max-height:300px;  overflow-y: scroll;">
                    <div class="card shadow mb-4">
                        <div class="card border-left-primary shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                            Preview</div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                                            <style>
                                                table{
                                                    font-family: Times New Roman;
                                                }
                                                table tr {
                                                    text-align:center; 
                                                }
                                                p.header{
                                                    font-size: 18pt;

                                                }
                                                p.cursive{
                                                    font-family:Verdana, sans-serif;
                                                    font-size: 16pt;
                                                    font-style: italic;
                                                    
                                                }
                                                p.name{
                                                    font-family:Arial;
                                                    font-size:12pt;
                                                }
                                                p.name{
                                                    font-family:Arial;
                                                    font-size:11pt;
                                                }
                                            </style>
                                                <table >
                                                    <tr>
                                                        <td colspan="3"></td>
                                                    </tr>
                                                    <tr style="text-align:center; ">
                                                        <td colspan="3" style="width:100%">
                                                            <br>
                                                            <br>
                                                            <p class="cursive">This</p>
                                                            <br>
                                                        </td>
                                                    </tr>
                                                    <tr style="text-align:center; ">
                                                        <td colspan="3">
                                                            <p style="font-size: 26pt; font-weight: bold;">CERTIFICATE OF PROFICIENCY</p>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="3"></td>
                                                    </tr>
                                                    <tr style="text-align:center;" >
                                                        <td style="width:70%" colspan="3">
                                                            <br>
                                                            <br>
                                                            <p class="cursive">is hereby presented to</p>
                                                            <p style="font-size: 20pt; font-weight: bold;">
                                                                NAME
                                                            </p>
                                                            <p style="font-size: 11pt;">
                                                                ADDRESS
                                                            </p>
                                                            <br>
                                                            <p style="font-size: 14pt;">
                                                                Certificate No. 123
                                                            </p>
                                                            <p style="font-size: 14pt;">
                                                                Accreditation No. 456
                                                            </p>
                                                            <br>
                                                            <p class="cursive">for successful participation, passing and achieving</p>
                                                            <p style="font-size: 22pt; font-weight: bold;">
                                                            Very Satisfactory
                                                            </p>
                                                        </td>
                                                    </tr>
                                                    <tr style="text-align:center;" >
                                                        <td style="width:80%" colspan="3">
                                                            <p class="cursive">performance in the</p>
                                                            <p style="font-size: 20pt; font-weight: bold;">“
                                                                {{$settings->certificate_theme}}
                                                            ” </p>
                                                            <br>
                                                            <?php
                                                                $given = \Carbon\Carbon::parse($settings->certificate_given_at);
                                                                \Carbon\Carbon::setToStringFormat('jS \d\a\y \o\f F Y');
                                                            ?>
                                                            <p class="cursive">
                                                                Given this {{$given}}
                                                            </p>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="width:40%">    
                                                        </td>
                                                        <td style="width:40%">  
                                                        </td>
                                                        <td style="width:20%">   
                                                            
                                                        </td>
                                                    </tr>
                                                </table>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>                  
                
                </div>
            </div>

        </div>
    </div> 



@endsection

@section('javascript')
<script>

</script>
@endsection